steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/anti-roblox-scam', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/anti-roblox-scam']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'anti-roblox-scam', '--image', 'gcr.io/$PROJECT_ID/anti-roblox-scam', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/anti-roblox-scam'
options:
  logsBucket: 'gs://jouw-build-logs-bucket' 